spring.application.name=ms-catalog
server.port=8081

# Configuración temporal para MySQL (luego la adaptaremos a Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/db_catalog?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

# Propiedades de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect